/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.trabalhoJava.Telas;

/**
 *
 * @author Vinicius
 */
import java.sql.*;
import javax.swing.JOptionPane;
import br.com.trabalhoJava.ClassesBeans.Usuario;
import br.com.trabalhoJava.DAO.UsuarioDao;

public class TelaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     *
     * @throws java.sql.SQLException
     */
    public TelaUsuario() throws SQLException {
        initComponents();

        UsuarioDao user = new UsuarioDao();
        //Laço para adicionar usuarios cadastrado no jComboBox
        for (Usuario p : user.ler()) {
            cboUsuConsulta.addItem(p.nomeS());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        txtFunNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFunCpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFunSenha = new javax.swing.JTextField();
        cboFunPerfil = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnUseCreate = new javax.swing.JButton();
        btnFunRemove = new javax.swing.JButton();
        btnFunAlterar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblCadUsuLogin = new javax.swing.JLabel();
        txtCadUsuLogin = new javax.swing.JTextField();
        cboUsuConsulta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnUsuBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuarios");
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        Nome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nome.setText("Nome");
        getContentPane().add(Nome);
        Nome.setBounds(100, 47, 35, 17);
        getContentPane().add(txtFunNome);
        txtFunNome.setBounds(156, 43, 319, 27);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Cpf");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 85, 22, 17);
        getContentPane().add(txtFunCpf);
        txtFunCpf.setBounds(156, 81, 319, 27);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 118, 38, 17);
        getContentPane().add(txtFunSenha);
        txtFunSenha.setBounds(156, 114, 319, 27);

        cboFunPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        getContentPane().add(cboFunPerfil);
        cboFunPerfil.setBounds(170, 190, 70, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Perfil");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(103, 190, 34, 17);

        btnUseCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/trabalhoJava/Icones/Add_user.png"))); // NOI18N
        btnUseCreate.setToolTipText("Adicionar");
        btnUseCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUseCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUseCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUseCreate);
        btnUseCreate.setBounds(160, 240, 70, 70);

        btnFunRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/trabalhoJava/Icones/Apagar_user.png"))); // NOI18N
        btnFunRemove.setToolTipText("Remover");
        btnFunRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFunRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnFunRemove);
        btnFunRemove.setBounds(280, 240, 70, 70);

        btnFunAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/trabalhoJava/Icones/update.png"))); // NOI18N
        btnFunAlterar.setToolTipText("Atualizar");
        btnFunAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFunAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFunAlterar);
        btnFunAlterar.setBounds(390, 240, 70, 70);

        jLabel4.setText("*O Preenchimento de todos os Campos são Obrigatorios!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(156, 23, 319, 14);

        lblCadUsuLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCadUsuLogin.setText("Login");
        getContentPane().add(lblCadUsuLogin);
        lblCadUsuLogin.setBounds(100, 155, 35, 17);
        getContentPane().add(txtCadUsuLogin);
        txtCadUsuLogin.setBounds(156, 151, 319, 27);

        cboUsuConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        getContentPane().add(cboUsuConsulta);
        cboUsuConsulta.setBounds(240, 360, 236, 27);

        jLabel5.setText("Usuarios Cadastrados:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(85, 356, 134, 27);

        btnUsuBuscar.setText("Buscar");
        btnUsuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuBuscar);
        btnUsuBuscar.setBounds(500, 360, 70, 23);

        setBounds(0, 0, 640, 480);
    }// </editor-fold>//GEN-END:initComponents
//Evento para Adicionar usuario
    private void btnUseCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUseCreateActionPerformed
        // TODO add your handling code here:
        //Instanciando objeto para chamar os atributos e metodos
        Usuario usr = new Usuario();
        UsuarioDao dao = new UsuarioDao();
        //Recebendo o conteudo dos canpos
        usr.setCpf(txtFunCpf.getText());
        usr.setNome(txtFunNome.getText());
        usr.setSenha(txtFunSenha.getText());
        usr.setLogin(txtCadUsuLogin.getText());
        usr.setPerfil((String) cboFunPerfil.getSelectedItem());
        //Chamando o metdo adicionar
        dao.adicionar(usr);
        //Limpando os campos
        txtCadUsuLogin.setText("");
        txtFunCpf.setText("");
        txtFunNome.setText("");
        txtCadUsuLogin.setText("");
        txtFunSenha.setText("");

    }//GEN-LAST:event_btnUseCreateActionPerformed
//Evento para Alterar usuario
    private void btnFunAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunAlterarActionPerformed
        // TODO add your handling code here:

        try {
            //Instanciando objeto para chamar os atributos e metodos
            Usuario usr = new Usuario();
            UsuarioDao dao = new UsuarioDao();
            //Recebendo o conteudo dos canpos
            usr.setCpf(txtFunCpf.getText());
            usr.setNome(txtFunNome.getText());
            usr.setSenha(txtFunSenha.getText());
            usr.setLogin(txtCadUsuLogin.getText());
            usr.setPerfil((String) cboFunPerfil.getSelectedItem());
            //Chamando o metdo alterar
            dao.alterar(usr);
            //Limpando os campos
            txtCadUsuLogin.setText("");
            txtFunCpf.setText("");
            txtFunNome.setText("");
            txtCadUsuLogin.setText("");
            txtFunSenha.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnFunAlterarActionPerformed
//Evento para Remover usuario
    private void btnFunRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunRemoveActionPerformed
        // TODO add your handling code here:

        try {
            //Instanciando objeto para chamar os atributos e metodos
            Usuario user = new Usuario();
            UsuarioDao dao = new UsuarioDao();
            //recebendo o conteudo do campo
            user.setCpf(txtFunCpf.getText());
            //Chamando o metodo deletar
            dao.deletar(user);
            //Limpando o campo
            txtFunCpf.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Exceção: " + e);
        }

    }//GEN-LAST:event_btnFunRemoveActionPerformed
//Evento para Buscar usuario
    private void btnUsuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuBuscarActionPerformed
        // TODO add your handling code here:
        //Instanciando objeto para chamar os atributos e metodos
        Usuario user = new Usuario();
        UsuarioDao dao = new UsuarioDao();
        //recebendo o conteudo do campo
        user.setNome((String) cboUsuConsulta.getSelectedItem());
        //Chamando o metodo
        dao.consultar(user);
        //preenchendo os campos
        txtCadUsuLogin.setText(user.getLogin());
        txtFunCpf.setText(user.getCpf());
        txtFunNome.setText(user.getNome());
        txtFunSenha.setText(user.getSenha());
        cboFunPerfil.setSelectedItem(user.getPerfil());

    }//GEN-LAST:event_btnUsuBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JButton btnFunAlterar;
    private javax.swing.JButton btnFunRemove;
    private javax.swing.JButton btnUseCreate;
    private javax.swing.JButton btnUsuBuscar;
    private javax.swing.JComboBox<String> cboFunPerfil;
    private javax.swing.JComboBox<String> cboUsuConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCadUsuLogin;
    private javax.swing.JTextField txtCadUsuLogin;
    private javax.swing.JTextField txtFunCpf;
    private javax.swing.JTextField txtFunNome;
    private javax.swing.JTextField txtFunSenha;
    // End of variables declaration//GEN-END:variables

}
