/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.trabalhoJava.Telas;

/**
 *
 * @author Vinicius
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import br.com.trabalhoJava.ClassesBeans.Produtos;
import br.com.trabalhoJava.DAO.ProdutoDao;
import java.text.DecimalFormat;
import java.text.NumberFormat;

public class TelaPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pedido
     *
     * @throws java.sql.SQLException
     */
    public TelaPedido() throws SQLException {
        initComponents();
        TelaProduto p = new TelaProduto();
        DefaultTableModel modelo = (DefaultTableModel) tblPedido.getModel();
        tblPedido.setRowSorter(new TableRowSorter(modelo));
        lerTabel();

    }

    public void lerTabel() throws SQLException {
        //criando um padrão de jtable
        DefaultTableModel modelo = (DefaultTableModel) tblPedido.getModel();
        modelo.setNumRows(0);
        ProdutoDao pdao = new ProdutoDao();
        //laço de repeição para ler as linhas da tabela
        for (Produtos p : pdao.ler()) {
            modelo.addRow(new Object[]{
                p.getCategoria(),
                p.getNome(),
                p.getPreco()

            });
        }
    }

    public void lerTabelPesq(String pesq) throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tblPedido.getModel();
        modelo.setNumRows(0);
        ProdutoDao pdao = new ProdutoDao();
        for (Produtos p : pdao.lerpesquisa(pesq)) {
            modelo.addRow(new Object[]{
                p.getCategoria(),
                p.getNome(),
                p.getPreco()

            });
        }

    }

  

    private void subtraiPreco(float valorTotal) {

        valorTotal -= Float.parseFloat(lblValorPedido.getText());
        lblPedidoTotal.setText(String.valueOf(valorTotal));

    }

    private void finPedido(float valorTotal) {
        if (valorTotal > 0) {
            NumberFormat formatador = new DecimalFormat("#0.00");
            int confirma = JOptionPane.showConfirmDialog(null, "Voce deseja finalizar o pedido de: " + formatador.format(valorTotal) + " Reais?", "ATENÇÃO!", JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                lblNomePedido.setText("-----");
                lblPedidoTotal.setText("0");
                lblValorPedido.setText("0");
                valor = 0;
                
                DefaultTableModel modelo = (DefaultTableModel) tblPedidoRemove.getModel();
                int i = 0;
                System.out.println(linhas);
                while(i <= linhas){
                    
            modelo.removeRow(0);
            
                ++i;}
                linhas = -1;
                
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        txtPesqProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnPedFinalizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPedidoTotal = new javax.swing.JLabel();
        lblNomePedido = new javax.swing.JLabel();
        lblValorPedido = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidoRemove = new javax.swing.JTable();
        btnPedAddSubtrai = new javax.swing.JButton();
        btnPedAddSoma = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pedido");
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        tblPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblPedido.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categria", "Nome", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedido);
        if (tblPedido.getColumnModel().getColumnCount() > 0) {
            tblPedido.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblPedido.getColumnModel().getColumn(1).setResizable(false);
            tblPedido.getColumnModel().getColumn(2).setResizable(false);
            tblPedido.getColumnModel().getColumn(2).setPreferredWidth(3);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 80, 570, 148);

        txtPesqProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqProdKeyReleased(evt);
            }
        });
        getContentPane().add(txtPesqProd);
        txtPesqProd.setBounds(170, 310, 340, 40);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pesquisa item do produto");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 270, 260, 30);

        btnPedFinalizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPedFinalizar.setText("Finalizar Pedido");
        btnPedFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedFinalizar);
        btnPedFinalizar.setBounds(350, 370, 161, 52);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1.setText("Pedido:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel2.setText("Valor:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel3.setText("Total:");
        jLabel3.setToolTipText("");

        lblPedidoTotal.setText("0");

        lblNomePedido.setText("--------");

        lblValorPedido.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(lblPedidoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomePedido, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(lblValorPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePedido)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorPedido)
                    .addComponent(jLabel2))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPedidoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(883, 15, 268, 167);

        tblPedidoRemove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedidoRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidoRemoveMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPedidoRemove);
        if (tblPedidoRemove.getColumnModel().getColumnCount() > 0) {
            tblPedidoRemove.getColumnModel().getColumn(0).setResizable(false);
            tblPedidoRemove.getColumnModel().getColumn(1).setResizable(false);
            tblPedidoRemove.getColumnModel().getColumn(1).setPreferredWidth(3);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(872, 256, 279, 122);

        btnPedAddSubtrai.setText("Remover Pedido");
        btnPedAddSubtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedAddSubtraiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedAddSubtrai);
        btnPedAddSubtrai.setBounds(948, 384, 138, 23);

        btnPedAddSoma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPedAddSoma.setText("Adicionar ao Pedido");
        btnPedAddSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedAddSomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedAddSoma);
        btnPedAddSoma.setBounds(170, 370, 160, 50);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel4.setText("Tabela de Pedidos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(964, 228, 126, 17);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tabela de Produtos Disponiveis");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 20, 380, 26);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/trabalhoJava/Icones/mad_wood-483965_640 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 690, 460);

        setBounds(0, 0, 697, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesqProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqProdKeyReleased
        try {
            // TODO add your handling code here:
            lerTabelPesq(txtPesqProd.getText());
        } catch (SQLException ex) {
            Logger.getLogger(TelaPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesqProdKeyReleased

    private void tblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidoMouseClicked
        // TODO add your handling code here:
     

        int setar = tblPedido.getSelectedRow();
        lblNomePedido.setText(tblPedido.getModel().getValueAt(setar, 1).toString());
        lblValorPedido.setText(tblPedido.getModel().getValueAt(setar, 2).toString());

   
    }//GEN-LAST:event_tblPedidoMouseClicked

    private void btnPedFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedFinalizarActionPerformed
        // TODO add your handling code here:

        //valorp.getValorTotal();
        finPedido(valor);
        
    }//GEN-LAST:event_btnPedFinalizarActionPerformed
    float valor = 0;
    int linhas = -1;
    
    private void btnPedAddSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedAddSomaActionPerformed
        // TODO add your handling code here:
        if (tblPedido.getSelectedRow() != -1) {
            NumberFormat formatador = new DecimalFormat("#0.00");
            valor += Float.parseFloat(lblValorPedido.getText());
            lblPedidoTotal.setText(String.valueOf(formatador.format(valor)));
            
            int setar = tblPedido.getSelectedRow();
            
            if(lblValorPedido.getText() != "0"){
            DefaultTableModel modelo = (DefaultTableModel) tblPedidoRemove.getModel();
            modelo.addRow(new String[]{lblNomePedido.getText(), lblValorPedido.getText()});
            linhas++;}
        }else {
            //Aviso para setar um produto
            JOptionPane.showMessageDialog(null, "Selecione um produto para Adicionar!");
        }

    }//GEN-LAST:event_btnPedAddSomaActionPerformed

    private void btnPedAddSubtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedAddSubtraiActionPerformed
        // TODO add your handling code here:
        if (tblPedidoRemove.getSelectedRow() != -1) {
        NumberFormat formatador = new DecimalFormat("#0.00");
        valor -= Float.parseFloat(lblValorPedido.getText());
        ((DefaultTableModel) tblPedidoRemove.getModel()).removeRow(tblPedidoRemove.getSelectedRow());
        lblPedidoTotal.setText(String.valueOf(formatador.format(valor)));
        linhas= linhas - 1;
        }else {
            //Aviso para setar um produto
            JOptionPane.showMessageDialog(null, "Selecione um produto para Remover!");
        }

    }//GEN-LAST:event_btnPedAddSubtraiActionPerformed

    private void tblPedidoRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidoRemoveMouseClicked
        // TODO add your handling code here:
        int setar = tblPedidoRemove.getSelectedRow();
        lblNomePedido.setText(tblPedidoRemove.getModel().getValueAt(setar, 0).toString());
        lblValorPedido.setText(tblPedidoRemove.getModel().getValueAt(setar, 1).toString());

    }//GEN-LAST:event_tblPedidoRemoveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedAddSoma;
    private javax.swing.JButton btnPedAddSubtrai;
    private javax.swing.JButton btnPedFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNomePedido;
    public javax.swing.JLabel lblPedidoTotal;
    public javax.swing.JLabel lblValorPedido;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTable tblPedidoRemove;
    private javax.swing.JTextField txtPesqProd;
    // End of variables declaration//GEN-END:variables

}
